version: "3.8"

services:
  puglla:
    image: ghcr.io/andrespuglla5655/puglla-examen:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"

        - "traefik.http.routers.puglla.entrypoints=http"
        - "traefik.http.routers.puglla.rule=Host(`puglla.byronrm.com`)"
        - "traefik.http.middlewares.puglla-https.redirectscheme.scheme=https"
        - "traefik.http.routers.puglla.middlewares=puglla-https"

        - "traefik.http.routers.puglla-secure.entrypoints=https"
        - "traefik.http.routers.puglla-secure.rule=Host(`puglla.byronrm.com`)"
        - "traefik.http.routers.puglla-secure.tls.certresolver=http"
        - "traefik.http.routers.puglla-secure.service=puglla"

        - "traefik.http.services.puglla.loadbalancer.server.port=3000"
        - "traefik.docker.network=traefik-public"

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
