version: "3.8"

services:
  quinche:
    image: ghcr.io/adqvelez-cloud/velez-alexis-examen:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"

        # Enrutamiento HTTP → HTTPS
        - "traefik.http.routers.quinche.entrypoints=http"
        - "traefik.http.routers.quinche.rule=Host(`quinche.byronrm.com`)"
        - "traefik.http.middlewares.quinche-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.quinche.middlewares=quinche-https-redirect"

        # HTTPS con certificado automático Let's Encrypt
        - "traefik.http.routers.quinche-secure.entrypoints=https"
        - "traefik.http.routers.quinche-secure.rule=Host(`quinche.byronrm.com`)"
        - "traefik.http.routers.quinche-secure.tls=true"
        - "traefik.http.routers.quinche-secure.tls.certresolver=http"
        - "traefik.http.routers.quinche-secure.service=quinche"

        # Puerto interno donde corre tu app (Node.js → 3000)
        - "traefik.http.services.quinche.loadbalancer.server.port=3000"

        # Red pública del traefik
        - "traefik.docker.network=traefik-public"

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
